Repository smith-chem-wisc/mzLib, pull requests merged in 2021-04, with the labels that each got.

#569 Update to net5.0
  BayesianEstimation/BayesianEstimation.csproj
  Chemistry/Chemistry.csproj
  FlashLFQ/FlashLFQ.csproj
  MassSpectrometry/MassSpectrometry.csproj
  Mgf/Mgf.csproj
  MzIdentML/MzIdentML.csproj
  MzLibUtil/MzLibUtil.csproj
  MzML/MzML.csproj
  Proteomics/Proteomics.csproj
  Test/DatabaseTests/TestDatabaseLoaders.cs
  Test/Properties/AssemblyInfo.cs
  Test/Test.csproj
  TestFlashLFQ/TestFlashLFQ.csproj
  ThermoRawFileReader/ThermoRawFileReader.csproj
  UsefulProteomicsDatabases/UsefulProteomicsDatabases.csproj
  mzLib.nuspec
  mzLib.sln
  mzPlot/mzPlot.csproj
  pepXML/pepXML.csproj
Labels: ready for review

#572 Add nuget badge
  README.md
Labels: Documentation, ready for review

#571 Only built with x64, so explicitly only use the x64 platform
  BayesianEstimation/BayesianEstimation.csproj
  Chemistry/Chemistry.csproj
  FlashLFQ/FlashLFQ.csproj
  MassSpectrometry/MassSpectrometry.csproj
  Mgf/Mgf.csproj
  MzIdentML/MzIdentML.csproj
  MzLibUtil/MzLibUtil.csproj
  MzML/MzML.csproj
  Proteomics/Proteomics.csproj
  Test/Test.csproj
  TestFlashLFQ/TestFlashLFQ.csproj
  ThermoRawFileReader/ThermoRawFileReader.csproj
  UsefulProteomicsDatabases/UsefulProteomicsDatabases.csproj
  mzLib.nuspec
  mzLib.sln
  mzPlot/mzPlot.csproj
  pepXML/pepXML.csproj
Labels: Maintenance, ready for review

#575 Add proteoform classifier code
  MzML/MzmlDynamicData.cs
  Proteomics/Protein/ProteoformLevelClassifier.cs
  Test/DatabaseTests/ProteoformClassificationUnitTest.csv
  Test/Test.csproj
  Test/TestProteinProperties.cs
  TestFlashLFQ/TestFlashLFQ.cs
Labels: ready for review
