Repository smith-chem-wisc/mzLib, pull requests merged in 2022-11, with the labels that each got.

#668 Deconvolution Refactoring
  mzLib/MassSpectrometry/Deconvolution/Algorithms/ClassicDeconvolutionAlgorithm.cs
  mzLib/MassSpectrometry/Deconvolution/Algorithms/DeconvolutionAlgorithm.cs
  mzLib/MassSpectrometry/Deconvolution/Algorithms/ExampleNewDeconvolutionAlgorithm.cs
  mzLib/MassSpectrometry/Deconvolution/Deconvoluter.cs
  mzLib/MassSpectrometry/Deconvolution/DeconvoluterExtensions.cs
  mzLib/MassSpectrometry/Deconvolution/Parameters/ClassicDeconvolutionParameters.cs
  mzLib/MassSpectrometry/Deconvolution/Parameters/DeconvolutionParameters.cs
  mzLib/MassSpectrometry/Deconvolution/Parameters/ExampleNewDeconvolutionParameters.cs
  mzLib/MassSpectrometry/MsDataScan.cs
  mzLib/MassSpectrometry/MzSpectra/MzSpectrum.cs
  mzLib/Test/TestDeconvolution.cs
  mzLib/mzLib.nuspec
  mzLib/mzLib.sln.DotSettings
Labels: ready for review

#673 Changed Masses and Intensities field in IsotopicDistribution
  mzLib/Chemistry/IsotopicDistribution.cs
Labels: Maintenance

#677 Edited normalization methods within SpectralSimilarity
  mzLib/MassSpectrometry/MzSpectra/SpectralSimilarity.cs
Labels: ready for review, ready for final review / merge

#665 added defaults to CZE migration time prediction
  mzLib/Proteomics/RetentionTimePrediction/CZE.cs
Labels: ready for final review / merge
