Repository smith-chem-wisc/mzLib, pull requests merged in 2024-04, with the labels that each got.

#765 Improved intensity pairs trying to make spectrum library comparisons faster
  mzLib/MassSpectrometry/MzSpectra/SpectralSimilarity.cs
  mzLib/Omics/SpectrumMatch/LibrarySpectrum.cs
  mzLib/Test/TestSpectralSimilarity.cs
Labels: Performance, ready for review

#770 Fragger Result reading
  mzLib/Readers/ExternalResults/IndividualResultRecords/MsFraggerPeptide.cs
  mzLib/Readers/ExternalResults/IndividualResultRecords/MsFraggerProtein.cs
  mzLib/Readers/ExternalResults/IndividualResultRecords/MsFraggerPsm.cs
  mzLib/Readers/ExternalResults/ResultFiles/MsFraggerPeptideFile.cs
  mzLib/Readers/ExternalResults/ResultFiles/MsFraggerProteinFile.cs
  mzLib/Readers/ExternalResults/ResultFiles/MsFraggerPsmFile.cs
  mzLib/Readers/Util/Converters.cs
  mzLib/Readers/Util/Software.cs
  mzLib/Readers/Util/SupportedFileTypes.cs
  mzLib/Test/FileReadingTests/ExternalFileTypes/FraggerPeptide_FragPipev21.1combined_peptide.tsv
  mzLib/Test/FileReadingTests/ExternalFileTypes/FraggerPeptide_FragPipev21.1individual_peptide.tsv
  mzLib/Test/FileReadingTests/ExternalFileTypes/FraggerProtein_FragPipev21.1combined_protein.tsv
  mzLib/Test/FileReadingTests/ExternalFileTypes/FraggerProtein_FragPipev21.1individual_protein.tsv
  mzLib/Test/FileReadingTests/ExternalFileTypes/FraggerPsm_FragPipev21.1_psm.tsv
  mzLib/Test/FileReadingTests/TestMsFraggerResultFiles.cs
  mzLib/Test/FileReadingTests/TestSupportedFileExtensions.cs
  mzLib/Test/Test.csproj
Labels: ready for review, New Feature

#778 Update dotnet.yml
  .github/workflows/dotnet.yml
Labels: Maintenance
