Repository smith-chem-wisc/mzLib, pull requests merged in 2025-07, with the labels that each got.

#908 if i create a branch from master will codecov actually have a base and generate a report
  mzLib/UsefulProteomicsDatabases/ProteinXmlEntry.cs
Labels: WIP

#911 MsDataScan Negative mode precursor charges states are now negative
  mzLib/MassSpectrometry/MsDataScan.cs
  mzLib/Test/FileReadingTests/TestMsDataFile.cs
Labels: bug, Maintenance

#902 GetAllXics
  mzLib/FlashLFQ/PeakIndexingEngine/IFlashLfqIndexingEngine.cs
  mzLib/MassSpectrometry/PeakIndexing/IndexingEngine.cs
  mzLib/Test/TestXic.cs
Labels: ready for review

#906 Mandatory sequence attributes read and write for protein XML
  mzLib/Proteomics/Protein/Protein.cs
  mzLib/Proteomics/Protein/UniProtSequenceAttributes.cs
  mzLib/Test/DatabaseTests/TestProteomicsReadWrite.cs
  mzLib/Test/ProteinDbLoaderTests.cs
  mzLib/Test/ProteinXmlEntryTests.cs
  mzLib/Test/TestProteinDatabase.cs
  mzLib/Test/UniProtSequenceAttributesTests.cs
  mzLib/UsefulProteomicsDatabases/DecoyGeneration/DecoyProteinGenerator.cs
  mzLib/UsefulProteomicsDatabases/ProteinDbWriter.cs
  mzLib/UsefulProteomicsDatabases/ProteinXmlEntry.cs
Labels: ready for review, New Feature

#886 MassIndexingEngine
  mzLib/FlashLFQ/PeakIndexingEngine/IFlashLfqIndexingEngine.cs
  mzLib/MassSpectrometry/PeakIndexing/ExtractedIonChromatogram.cs
  mzLib/MassSpectrometry/PeakIndexing/IndexedMass.cs
  mzLib/MassSpectrometry/PeakIndexing/IndexingEngine.cs
  mzLib/MassSpectrometry/PeakIndexing/MassIndexingEngine.cs
  mzLib/MassSpectrometry/PeakIndexing/PeakSpline/XicSpline.cs
  mzLib/Test/TestXic.cs
  mzLib/TestFlashLFQ/IndexingEngineTests.cs
Labels: ready for review

#922 Oligo fragmentation with null parent
  mzLib/Test/Transcriptomics/TestOligoWithSetMods.cs
  mzLib/Transcriptomics/Digestion/OligoWithSetMods.cs
Labels: bug, Maintenance
