Repository smith-chem-wisc/mzLib, pull requests merged in 2025-08, with the labels that each got.

#924 GetAllXics with cutPeak
  mzLib/MassSpectrometry/PeakIndexing/ExtractedIonChromatogram.cs
  mzLib/MassSpectrometry/PeakIndexing/IndexingEngine.cs
  mzLib/Test/TestXic.cs
Labels: ready for review

#928 Adjust XIC spline to adapt double-to-float change in IIndexedPeak
  mzLib/MassSpectrometry/PeakIndexing/IndexingEngine.cs
  mzLib/MassSpectrometry/PeakIndexing/PeakSpline/XicSpline.cs
  mzLib/Test/TestXic.cs
  mzLib/TestFlashLFQ/IndexingEngineTests.cs
  mzLib/TestFlashLFQ/TestFlashLFQ.cs
Labels: ready for review

#929 Added support for Dinosaur output to readers
  mzLib/Readers/ExternalResults/IndividualResultRecords/DinosaurFeature.cs
  mzLib/Readers/ExternalResults/ResultFiles/DinosaurTsvFile.cs
  mzLib/Readers/Util/Software.cs
  mzLib/Readers/Util/SupportedFileTypes.cs
  mzLib/Test/FileReadingTests/ExternalFileTypes/DinoSnippet.features.tsv
  mzLib/Test/FileReadingTests/TestDinosaurTsv.cs
  mzLib/Test/Test.csproj
Labels: ready for review

#931 Add interfaces for external decon results and implement for Ms1Feature/Dinosaur classes
  mzLib/Readers/BaseClasses/IMs1FeatureFile.cs
  mzLib/Readers/BaseClasses/ISingleChargeMs1Feature.cs
  mzLib/Readers/ExternalResults/IndividualResultRecords/DinosaurFeature.cs
  mzLib/Readers/ExternalResults/IndividualResultRecords/Ms1Feature.cs
  mzLib/Readers/ExternalResults/ResultFiles/DinosaurTsvFile.cs
  mzLib/Readers/ExternalResults/ResultFiles/Ms1FeatureFile.cs
  mzLib/Test/FileReadingTests/TestDinosaurTsv.cs
  mzLib/Test/FileReadingTests/TestMsFeature.cs
Labels: ready for review

#933 Parse peptide full sequence containing amino acid substitutions
  mzLib/Omics/IBioPolymerWithSetMods.cs
  mzLib/Test/TestPeptideWithSetMods.cs
Labels: ready for review

#935 Parallelized SpectralMatchFromTsv Reading
  mzLib/Readers/InternalResults/ResultFiles/SpectrumMatchTsvReader.cs
Labels: enhancement, Maintenance, ready for review

#939 Update ParseModifications output and modification regex.
  mzLib/MzLibUtil/ClassExtensions.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/SpectrumMatchFromTsv.cs
  mzLib/Test/FileReadingTests/TestPsmFromTsv.cs
  mzLib/Test/TestMzLibUtil.cs
Labels: enhancement, ready for review, Breaks Integration Tests

#941 Snip those MzMLs
  mzLib/Readers/MsDataFileExtensions.cs
  mzLib/Test/FileReadingTests/TestExportSnipAsMzML.cs
Labels: ready for review
