Repository smith-chem-wisc/mzLib, pull requests merged in 2025-01, with the labels that each got.

#820 Db writer fix
  mzLib/Test/DatabaseTests/TestDatabaseLoaders.cs
  mzLib/UsefulProteomicsDatabases/ProteinDbWriter.cs
Labels: bug

#822 Object Pooling
  mzLib/MzLibUtil/MzLibUtil.csproj
  mzLib/MzLibUtil/MzLibUtil.csproj.DotSettings
  mzLib/MzLibUtil/ObjectPools/DictionaryPool.cs
  mzLib/MzLibUtil/ObjectPools/HashSetPool.cs
  mzLib/MzLibUtil/ObjectPools/ListPool.cs
  mzLib/Omics/Digestion/DigestionAgent.cs
  mzLib/Test/ObjectPoolTests.cs
  mzLib/mzLib.nuspec
Labels: Maintenance, ready for review, New Feature

#823 Digestion Consolidation and Optimization
  mzLib/Omics/BioPolymerWithSetModsExtensions.cs
  mzLib/Omics/Digestion/DigestionProduct.cs
  mzLib/Omics/Modifications/ModificationLocalization.cs
  mzLib/Proteomics/ProteolyticDigestion/Protease.cs
  mzLib/Proteomics/ProteolyticDigestion/ProteolyticPeptide.cs
  mzLib/Test/FileReadingTests/TestMsFraggerCombinedResults.cs
  mzLib/Transcriptomics/Digestion/NucleolyticOligo.cs
  mzLib/mzLib.nuspec
Labels: Maintenance, ready for review

#825 Digestion: Fixed mod terminal fix and variable mod ordering
  mzLib/Omics/Digestion/DigestionProduct.cs
  mzLib/Omics/Modifications/Modification.cs
  mzLib/Omics/Modifications/ModificationLocalization.cs
  mzLib/Omics/Modifications/ModificationMotif.cs
  mzLib/Test/DatabaseTests/SingleEntry_ModOrder1.xml
  mzLib/Test/DatabaseTests/SingleEntry_ModOrder2.xml
  mzLib/Test/Test.csproj
  mzLib/Test/TestModifications.cs
  mzLib/Test/TestProteinDigestion.cs
Labels: bug, ready for review, Breaks Integration Tests

#827 Put those mods back where they came from or so help me
  mzLib/Omics/Digestion/DigestionProduct.cs
  mzLib/Omics/Modifications/ModificationLocalization.cs
  mzLib/Test/TestProteinDigestion.cs
  mzLib/Test/Transcriptomics/TestDigestion.cs
Labels: bug, ready for review

#831 Undo Rounding
  mzLib/MassSpectrometry/MzSpectra/MzSpectrum.cs
  mzLib/Test/FileReadingTests/TestMsDataFileToResultsAdapter.cs
  mzLib/Test/FileReadingTests/TestMzML.cs
  mzLib/Test/FileReadingTests/TestRawFileReader.cs
  mzLib/TestFlashLFQ/TestFlashLFQ.cs
Labels: ready for review

#829 Change github action workflow to upload MM installer artifact
  .github/workflows/dotnet.yml
Labels: enhancement, ready for review

#830 Included CsvHelper as dependency in nuspec
  mzLib/mzLib.nuspec
Labels: bug, ready for review
