Repository smith-chem-wisc/mzLib, pull requests merged in 2025-04, with the labels that each got.

#845 Xl PsmTsv and Library Reading
  mzLib/Omics/SpectrumMatch/CrosslinkLibrarySpectrum.cs
  mzLib/Omics/SpectrumMatch/LibrarySpectrum.cs
  mzLib/Omics/SpectrumMatch/SpectrumMatchFromTsv.cs
  mzLib/Omics/SpectrumMatch/SpectrumMatchFromTsvHeader.cs
  mzLib/Proteomics/PSM/PsmFromTsv.cs
  mzLib/Proteomics/PSM/PsmTsvHeader_Glyco.cs
  mzLib/Readers/Readers.csproj
  mzLib/Readers/SearchResults/OsmFromTsvFile.cs
  mzLib/Readers/SearchResults/SpectrumMatchTsvReader.cs
  mzLib/Readers/Util/SupportedFileTypes.cs
  mzLib/Test/FileReadingTests/SearchResults/XL_Intralinks.tsv
  mzLib/Test/FileReadingTests/TestPsmFromTsv.cs
  mzLib/Test/Test.csproj
  mzLib/Test/TestLibrarySpectrum.cs
  mzLib/Transcriptomics/SpectrumMatch/OsmFromTsv.cs
  mzLib/UsefulProteomicsDatabases/ProteinDbWriter.cs
  mzLib/UsefulProteomicsDatabases/Transcriptomics/RnaDbLoader.cs
  mzLib/mzLib.sln.DotSettings
Labels: Maintenance, ready for review, New Feature, Breaks Integration Tests

#854 Base Sequence From Full Sequence - Custom Delimiters
  mzLib/Omics/IBioPolymerWithSetMods.cs
  mzLib/Test/Omics/IBioPolymerWithSetModsTests.cs
  mzLib/mzLib.sln.DotSettings
Labels: enhancement, Maintenance, ready for review

#852 IsMBR replacement by DetectionType
  mzLib/FlashLFQ/ChromatographicPeak.cs
  mzLib/FlashLFQ/DetectionType.cs
  mzLib/FlashLFQ/FlashLFQResults.cs
  mzLib/FlashLFQ/FlashLfqEngine.cs
  mzLib/FlashLFQ/MbrScorer.cs
  mzLib/FlashLFQ/PEP/PepAnalysisEngine.cs
  mzLib/TestFlashLFQ/ChromatographicPeakTests.cs
  mzLib/TestFlashLFQ/TestFlashLFQ.cs
  mzLib/TestFlashLFQ/TestPipEcho.cs
Labels: ready for review, Refactor

#860 Refactoring FlashLFQ: Part1
  mzLib/FlashLFQ/ChromatographicPeak.cs
  mzLib/FlashLFQ/FlashLFQResults.cs
  mzLib/FlashLFQ/FlashLfqEngine.cs
  mzLib/FlashLFQ/MBR/MbrChromatographicPeak.cs
  mzLib/FlashLFQ/MBR/MbrScorer.cs
  mzLib/FlashLFQ/MBR/PEP/ChromatographicPeakData.cs
  mzLib/FlashLFQ/MBR/PEP/DonorGroup.cs
  mzLib/FlashLFQ/MBR/PEP/PepAnalysisEngine.cs
  mzLib/FlashLFQ/MBR/PEP/TruePositivePrediction.cs
  mzLib/FlashLFQ/MBR/RetentionTimeCalibDataPoint.cs
  mzLib/FlashLFQ/MBR/RtInfo.cs
  mzLib/FlashLFQ/PeakIndexing/IndexedMassSpectralPeak.cs
  mzLib/FlashLFQ/PeakIndexing/PeakIndexingEngine.cs
  mzLib/TestFlashLFQ/ChromatographicPeakTests.cs
  mzLib/TestFlashLFQ/TestFlashLFQ.cs
  mzLib/TestFlashLFQ/TestPipEcho.cs
Labels: ready for review, Refactor

#859 Decoy scrambler generalization
  mzLib/Omics/BioPolymer/IBioPolymer.cs
  mzLib/Proteomics/Protein/Protein.cs
  mzLib/Test/DatabaseTests/TestDecoyProteinValidator.cs
  mzLib/Test/TestProteinDigestion.cs
  mzLib/Test/Transcriptomics/TestVariantOligo.cs
  mzLib/Transcriptomics/NucleicAcid.cs
  mzLib/Transcriptomics/RNA.cs
  mzLib/UsefulProteomicsDatabases/DecoyGeneration/DecoyProteinGenerator.cs
  mzLib/UsefulProteomicsDatabases/DecoyGeneration/DecoySequenceValidator.cs
  mzLib/UsefulProteomicsDatabases/DecoyGeneration/DecoyType.cs
  mzLib/UsefulProteomicsDatabases/DecoyGeneration/RnaDecoyGenerator.cs
Labels: enhancement, Maintenance, ready for review

#864 Reader extensions
  mzLib/FlashLFQ/ResultsReading/MzLibExtensions.cs
  mzLib/Readers/BaseClasses/IQuantifiableRecord.cs
  mzLib/Readers/BaseClasses/IQuantifiableResultFile.cs
  mzLib/Readers/BaseClasses/IResultFile.cs
  mzLib/Readers/BaseClasses/ResultFile.cs
  mzLib/Readers/ExternalResults/IndividualResultRecords/MsFraggerPsm.cs
  mzLib/Readers/ExternalResults/ResultFiles/MsDataFileToResultFileAdapter.cs
  mzLib/Readers/ExternalResults/ResultFiles/MsFraggerCombinedResults.cs
  mzLib/Readers/ExternalResults/ResultFiles/MsFraggerPsmFile.cs
  mzLib/Readers/ExternalResults/ResultFiles/MsPathFinderTResultFile.cs
  mzLib/Readers/ExternalResults/ResultFiles/TopFDMzrtFile.cs
  mzLib/Readers/FileReader.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/OsmFromTsv.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/PsmFromTsv.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/PsmTsvHeader_Glyco.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/QuantifiedPeak.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/SpectrumMatchFromTsv.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/SpectrumMatchFromTsvHeader.cs
  mzLib/Readers/InternalResults/ResultFiles/OsmFromTsvFile.cs
  mzLib/Readers/InternalResults/ResultFiles/PsmFromTsvFile.cs
  mzLib/Readers/InternalResults/ResultFiles/QuantifiedPeakFile.cs
  mzLib/Readers/InternalResults/ResultFiles/SpectrumMatchFromTsvFile.cs
  mzLib/Readers/InternalResults/ResultFiles/SpectrumMatchTsvReader.cs
  mzLib/Readers/Util/SupportedFileTypes.cs
  mzLib/Test/FileReadingTests/TestQuantifiedPeak.cs
  mzLib/Test/FileReadingTests/TestSupportedFileExtensions.cs
  mzLib/TestFlashLFQ/TestIdentificationAdapter.cs
Labels: enhancement, ready for review

#867 Implemented IQuantifiableRecord/File for SpectrumMatchFromTsv/File
  mzLib/FlashLFQ/ResultsReading/MzLibExtensions.cs
  mzLib/Readers/BaseClasses/IQuantifiableRecord.cs
  mzLib/Readers/ExternalResults/IndividualResultRecords/MsFraggerPsm.cs
  mzLib/Readers/ExternalResults/ResultFiles/MsFraggerCombinedResults.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/PsmFromTsv.cs
  mzLib/Readers/InternalResults/IndividualResultRecords/SpectrumMatchFromTsv.cs
  mzLib/Readers/InternalResults/ResultFiles/OsmFromTsvFile.cs
  mzLib/Readers/InternalResults/ResultFiles/PsmFromTsvFile.cs
  mzLib/Readers/InternalResults/ResultFiles/SpectrumMatchFromTsvFile.cs
  mzLib/Readers/InternalResults/ResultFiles/SpectrumMatchTsvReader.cs
  mzLib/Test/FileReadingTests/SearchResults/BottomUpExample.psmtsv
  mzLib/Test/FileReadingTests/TestMsFraggerResultFiles.cs
  mzLib/Test/FileReadingTests/TestPsmFromTsv.cs
  mzLib/Test/Test.csproj
  mzLib/Test/TestDeconvolution.cs
  mzLib/TestFlashLFQ/TestIdentificationAdapter.cs
Labels: enhancement, ready for review
